language:
  - bash

services:
  - docker

sudo: true

jobs:
  include:
    - stage: build
      script: ./ci/bin/docker_build_and_push.sh 1.0 code-maat code-maat:1 code-maat:1.0 code-maat:1.0.1 code-maat:1.0.1-alpine

